services:
  db:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
      - 9009:9009
      - 9100:9100
      - 9000:9000
    volumes:
      - ./clickhouse-docker-mount:/etc/clickhouse-server