name: Build

on:
  push:
    branches:
      - master
      - develop
      - 0.2.x
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**/CHANGELOG"

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**/CHANGELOG"

  workflow_dispatch:
    inputs:
      pr:
        description: "Pull request#"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
        # most recent LTS releases as well as latest stable builds
        clickhouse: ["19.14", "20.3", "20.8", "20.10", "20.12", "21.2", "latest"]
    name: Build using JDK ${{ matrix.java }} against ClickHouse ${{ matrix.clickhouse }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Check out PR
        run: |
          git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 \
            origin pull/${{ github.event.inputs.pr }}/merge:merged-pr && git checkout merged-pr
        if: github.event.inputs.pr != ''
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      # Step that does that actual cache save and restore
      - name: Cache maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Generate build properties
        uses: actions/github-script@v3
        id: props
        env:
          CURRENT_VERSION: ${{ steps.version.outputs.value }}
        with:
          script: |
            const timezones = [
              'Asia/Chongqing', 'America/Los_Angeles', 'Etc/UTC', 'Europe/Berlin', 'Europe/Moscow'
            ];
            // surprise me
            return {
                clickhouse: timezones[Math.floor(Math.random() * Math.floor(timezones.length))] || '',
                java: timezones[Math.floor(Math.random() * Math.floor(timezones.length))] || ''
            };
      - name: Build with Maven
        run: |
          find . -type f -name "pom.xml" -exec sed -i -e 's|.*argLine.*timezone=.*||g' '{}' \;
          mvn --batch-mode --update-snapshots \
            -DclickhouseVersion=${{ matrix.clickhouse }} \
            -DclickhouseTimezone=${{ fromJSON(steps.props.outputs.result).clickhouse }} \
            -Duser.timezone=${{ fromJSON(steps.props.outputs.result).java }} verify
