name: Build

on:
  push:
    branches:
      - master
      - develop
      - 0.2.x
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**/CHANGELOG"

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**/CHANGELOG"

  workflow_dispatch:
    inputs:
      pr:
        description: "Pull request#"
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # most recent LTS releases as well as latest stable builds
        clickhouse: ["21.3", "21.8", "latest"]
        # http2 here represents http protocol + JDK HttpClient(http_connection_provider=HTTP_CLIENT)
        protocol: ["http", "http2", "grpc"]
        exclude:
          - clickhouse: "21.3"
            protocol: grpc
          - clickhouse: "21.8"
            protocol: grpc
      fail-fast: false
    timeout-minutes: 30
    name: Build against ClickHouse ${{ matrix.clickhouse }} (${{ matrix.protocol }})
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Check out PR
        run: |
          git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 \
            origin pull/${{ github.event.inputs.pr }}/merge:merged-pr && git checkout merged-pr
        if: github.event.inputs.pr != ''
      - name: Install JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          targets: 'JDK11_HOME'
      - name: Setup Toolchain
        shell: bash
        run: |
          mkdir -p $HOME/.m2 \
          && cat << EOF > $HOME/.m2/toolchains.xml
          <?xml version="1.0" encoding="UTF8"?>
          <toolchains>
            <toolchain>
              <type>jdk</type>
              <provides>
                <version>11</version>
              </provides>
              <configuration>
                <jdkHome>${{ env.JDK11_HOME }}</jdkHome>
              </configuration>
            </toolchain>
          </toolchains>
          EOF
      - name: Install JDK 8 and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'maven'
      # or take below workaround as mentioned at https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080
      # -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
      - name: Check
        run: mvn --batch-mode --update-snapshots -Drelease -DskipTests install
      - name: Build
        run: |
          mvn --batch-mode --update-snapshots -Drelease -DclickhouseVersion=${{ matrix.clickhouse }} -Dprotocol=${{ matrix.protocol }} verify
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: result ${{ github.job }}
          path: |
            **/target/failsafe-reports
            **/target/surefire-reports
