name: Build

on:
  push:
    branches:
      - master
      - develop
      - 0.2.x
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**/CHANGELOG"

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**/CHANGELOG"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
        # most recent LTS releases as well as latest stable builds
        clickhouse: ["19.14", "20.3", "20.8", "20.10", "20.12", "21.2", "latest"]
    name: Build using JDK ${{ matrix.java }} against ClickHouse ${{ matrix.clickhouse }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      # Step that does that actual cache save and restore
      - name: Cache maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -DclickhouseVersion=${{ matrix.clickhouse }} verify
