name: TimeZone

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**/CHANGELOG"

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**/CHANGELOG"

  workflow_dispatch:
    inputs:
      pr:
        description: "Pull request#"
        required: false

jobs:
  timezone:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        serverTz: ["Asia/Chongqing", "America/Los_Angeles", "Etc/UTC", "Europe/Berlin", "Europe/Moscow"]
        clientTz: ["Asia/Chongqing", "America/Los_Angeles", "Etc/UTC", "Europe/Berlin", "Europe/Moscow"]
      fail-fast: false
    name: "TimeZone(C/S): ${{ matrix.clientTz }} vs. ${{ matrix.serverTz }}"
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Check out PR
        run: |
          git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 \
            origin pull/${{ github.event.inputs.pr }}/merge:merged-pr && git checkout merged-pr
        if: github.event.inputs.pr != ''
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Install dependencies
        run: |
          mvn --batch-mode --update-snapshots \
            --projects clickhouse-client -DskipTests \
            --also-make install
      - name: Test JDBC driver
        run: |
          mvn --batch-mode --update-snapshots \
            --projects clickhouse-jdbc \
            -DclickhouseTimezone=${{ matrix.serverTz }} \
            -DclickhouseVersion=21.8 \
            -Duser.timezone=${{ matrix.clientTz }} \
            --also-make clean verify
