name: Verify

on:
  workflow_dispatch:
    inputs:
      clickhouse:
        description: "ClickHouse Version"
        required: true
        default: "latest"
      java:
        description: "Java Version"
        required: true
        default: "8"
      pr:
        description: "Pull Request#"
        required: false

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify pull request \#${{ github.event.inputs.pr }} using JDK ${{ github.event.inputs.java }} against ClickHouse ${{ github.event.inputs.clickhouse }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        if: github.event.inputs.pr == ''
      - name: Check out pull request \#${{ github.event.inputs.pr }}
        uses: actions/checkout@v2
        if: github.event.inputs.pr != ''
        with:
          ref: refs/remotes/pull/${{ github.event.inputs.pr }}/merge
      - name: Set up JDK ${{ github.event.inputs.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ github.event.inputs.java }}
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -DclickhouseVersion=${{ matrix.clickhouse }} verify
